version: "3.8"

services:
  # e-commerce-api:
  #   build:
  #     context: src\E-Commerce.API\
  #     dockerfile: Dockerfile
  #   pull_policy: build
  #   ports:
  #     - "8080:80"
  #   networks:
  #     - broker-kafka

  zookeeper:
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    networks:
      - broker-kafka

  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
    networks:
      - broker-kafka
    depends_on:
      - zookeeper

networks:
  broker-kafka:
    driver: bridge
